//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorMaster
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FloorMasterEntities : DbContext
    {
        public static FloorMasterEntities _context;
        public static FloorMasterEntities GetContext()
        {
            if (_context == null)
            {
                _context = new FloorMasterEntities();
            }
            return _context;
        }
        public FloorMasterEntities()
            : base("name=FloorMasterEntities")
        {
        }
     
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationProductPartners> ApplicationProductPartners { get; set; }
        public virtual DbSet<ManyArticle> ManyArticle { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialProducts> MaterialProducts { get; set; }
        public virtual DbSet<MaterialProviderHistory> MaterialProviderHistory { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SalePatnerPlaces> SalePatnerPlaces { get; set; }
        public virtual DbSet<SalePlaces> SalePlaces { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeMaterial> TypeMaterial { get; set; }
        public virtual DbSet<TypePartners> TypePartners { get; set; }
        public virtual DbSet<TypeProduct> TypeProduct { get; set; }
        public virtual DbSet<TypeProvider> TypeProvider { get; set; }
        public virtual DbSet<workers> workers { get; set; }
        public virtual DbSet<CostPriceHistory> CostPriceHistory { get; set; }
        public virtual DbSet<MaterialHistory> MaterialHistory { get; set; }
        public virtual DbSet<MinCostPriceHistory> MinCostPriceHistory { get; set; }
        public virtual DbSet<ProductHistory> ProductHistory { get; set; }
    }
}
