//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialHistory = new HashSet<MaterialHistory>();
            this.MaterialProducts = new HashSet<MaterialProducts>();
            this.MaterialProviderHistory = new HashSet<MaterialProviderHistory>();
        }
    
        public int Id { get; set; }
        public int TypeID { get; set; }
        public string Name { get; set; }
        public int ProviderID { get; set; }
        public decimal QuantityPerPackage { get; set; }
        public string UnitOfMeasurement { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public decimal Cost { get; set; }
        public int QuantityInStock { get; set; }
        public Nullable<int> MinimumAllowedQuantity { get; set; }
    
        public virtual TypeMaterial TypeMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialHistory> MaterialHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProducts> MaterialProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProviderHistory> MaterialProviderHistory { get; set; }
    }
}
