//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.MaterialProducts = new HashSet<MaterialProducts>();
            this.CostPriceHistory = new HashSet<CostPriceHistory>();
            this.MinCostPriceHistory = new HashSet<MinCostPriceHistory>();
            this.ProductHistory = new HashSet<ProductHistory>();
        }
    
        public int Article { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
        public string Image { get; set; }
        public decimal MinimalCost { get; set; }
        public Nullable<decimal> PackageWidth { get; set; }
        public Nullable<decimal> PackageHight { get; set; }
        public Nullable<decimal> PackageLenght { get; set; }
        public Nullable<decimal> WeightWithoutPack { get; set; }
        public Nullable<decimal> WeightPack { get; set; }
        public string QualityCertificate { get; set; }
        public Nullable<int> StandartNumber { get; set; }
        public Nullable<decimal> ProductionTimeCraft { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<int> WorkshopNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProducts> MaterialProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostPriceHistory> CostPriceHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MinCostPriceHistory> MinCostPriceHistory { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductHistory> ProductHistory { get; set; }
    }
}
