//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePatnerPlaces
    {
        public int IDPartners { get; set; }
        public int IDPlaces { get; set; }
        public int ID { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual SalePlaces SalePlaces { get; set; }
    }
}
