//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class workers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public workers()
        {
            this.ApplicationProductPartners = new HashSet<ApplicationProductPartners>();
            this.MaterialProviderHistory = new HashSet<MaterialProviderHistory>();
        }
    
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronomyc { get; set; }
        public int Seriapassport { get; set; }
        public int Numberpassport { get; set; }
        public System.DateTime Birthday { get; set; }
        public string NameBank { get; set; }
        public string AccountNumberBank { get; set; }
        public string BIKBank { get; set; }
        public string CorrespondentAccountBank { get; set; }
        public bool HavingFamily { get; set; }
        public string HealthStatus { get; set; }
        public int RoleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationProductPartners> ApplicationProductPartners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProviderHistory> MaterialProviderHistory { get; set; }
        public virtual Role Role { get; set; }
    }
}
